<?php
require("../../connect.php");
require("../../validation/validation.php");
require("./add.php");
require("./edit.php");
require("./delete.php");
require("./get.php");
require("./addBatch.php");
require("./editBatch.php");
require("./getProductBatchesdropdown.php");
require("./getProductsIdName.php");
?>